apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-app-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: prod-cluster
        url: https://kubernetes.default.svc
      - cluster: staging
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/priyam930/ArgoCD_2025.git
        targetRevision: main
        path: 'multienv/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: default
