apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpdweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpdweb
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
